name: google-chat-pull-request
on:
  pull_request:
    types: [ opened, reopened, ready_for_review, labeled, edited, closed ]
jobs:
  chat:
    runs-on: ubuntu-latest
    steps:
      - name: Post Google Chat message
        env:
          COMMIT_VAR: "${{github.event.pull_request.user.login}} ${{ github.event.action }} ${{ github.event.pull_request.title }}. ${{ github.event.pull_request.html_url }}"
        uses: julb/action-post-googlechat-message@v1
        with:
          message: ${COMMIT_VAR}
          gchat_webhook_url: ${{ secrets.GOOGLE_CHAT_WEBHOOK }}
