name: debug
on:
  push:
    branches: [ master ]
  pull_request:
    types: [ opened, reopened, ready_for_review, closed ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: show github variable
        run: echo ${{ on.pull_request.type }}
#      - name: Post Google Chat message
#        uses: julb/action-post-googlechat-message@v1
#        with:
#          message: "Hello from Github Action!"
#          gchat_webhook_url: ${{ secrets.GCHAT_WEBHOOK_URL }}
