name: debug
on:
  push:
    branches: [ master, test ]
  pull_request:
    types: [ opened, reopened, ready_for_review, closed ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: show github variable
        run: |
          echo ${{ github.event.action }}
          echo ${{ github.event.pull_request.title }}
          echo ${{ github.event.pull_request.url }}
          echo ${{ github.event.actor.login }}
          echo ${{ github.event.repo.url }}
#      - name: Post Google Chat message
#        uses: julb/action-post-googlechat-message@v1
#        with:
#          message: "Hello from Github Action!"
#          gchat_webhook_url: ${{ secrets.GCHAT_WEBHOOK_URL }}
